
plot3([0,1],[0,0],[0,0],'k', 'DisplayName', 'orthogonal distance to board')
xlim([-0.1,1])
ylim([-0.1,.6])
zlim([0,.6])
hold on
plot3([0,1],[0,.5],[0,.5], 'k', 'DisplayName', 'Altitude after Azimuth')
plot3([0,1],[0,.5],[0,0], 'k', 'DisplayName', '(Ortogonal Distance to Board)/Cos(theta_azimuth)')
plot3([1,1],[.5,.5],[0,.5], 'k', 'DisplayName', 'fvhg')
plot3([1,1],[0,.5],[0,0], 'k', 'DisplayName', 'fvhg')
plot3([1,1], [.5,0], [.5,.5], 'k')
plot3([1,1], [0,0], [0,.5], 'k')
text1 = text(0, -0.01, 0, '$Distance To Board_{\ Orthongal}$', ...
    'interpreter','latex', ...
    'FontSize', 12, ...
    'Rotation', 60)
text2 = text(0.4, 0.4, 0, '$\displaystyle\frac{Distance To Board_{\ Orthognal}}{cos(\theta_{az})}$', ...
    'interpreter','latex', ...
    'FontSize', 12, ...
    'Rotation', -8) 
text3 = text(1, 0.52, 0.1, '$Height Above Zero_{\ Theoretical}$', ...
    'interpreter','latex', ...
    'FontSize', 16, ...
    'Rotation', 90)
text4 = text(1, .3, 0.3, '$White \ Board$', ...
    'interpreter','latex', ...
    'FontSize', 16, ...
    'Rotation', 0)
text5 = text(0.4, 0.025, 0, '$\theta_{az}$', ...
    'interpreter','latex', ...
    'FontSize', 16, ...
    'Rotation', 0)
text6 = text(.2, 0.07, .025, '$\theta_{alt}$', ...
    'interpreter','latex', ...
    'FontSize', 16, ...
    'Rotation', 0)
hold off
view([-87 7])